SELECT 
DISTINCT a.name as TABLE_NAME,  kcu.TABLE_SCHEMA
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS kcu 
RIGHT OUTER JOIN sys.sysobjects AS a 
	ON kcu.TABLE_NAME = a.name 
WHERE xtype = 'U' AND LOWER(kcu.TABLE_SCHEMA) = LOWER('{0}')
